package database;

/*
 * Copyright
 */
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Factorial JPA.
 *
 * @since 0.0.1
 */
@Entity
@Table(schema = "public", name = "factorial")
public class FactorialJpa {

    /**
     * Primary key.
     * Autogenerated.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false, updatable = false)
    private Long id;

    /**
     * Name of algorithm.
     */
    @Column(name = "name")
    private String name;

    /**
     * Get ID of algorithm.
     * @return Id.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Get name of algorithm.
     * @return Name.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Set name of algorithm.
     * @param var Algorithm name.
     */
    public void setName(final String var) {
        this.name = var;
    }
}


